name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ruff mypy pytest pytest-qt playwright
      - run: playwright install --with-deps
      - run: ruff .
      - run: mypy beichtsthul_modern
      - run: pytest
      - name: Run Contrast Audit
        run: python beichtsthul_modern/utils/contrast_audit.py